### ISSUE TITLE
Dependency Error on OSX Yosemite

### ISSUE THREAD

**Issue by lhornby** [perkowitz/issho#11]
Any ideas please?

"Failed to execute goal on project issho: Could not resolve dependencies for project net.perkowitz:issho:jar:1.0: The following artifacts could not be resolved: net.thecodersbreakfast:lp4j-api:jar:1.0, net.thecodersbreakfast:lp4j-midi:jar:1.0: Could not find artifact net.thecodersbreakfast:lp4j-api:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]"

mvn - version 
"Apache Maven 3.3.9 "
"Java version: 1.8.0_111"

**Comment by lhornby** [comment]
Solved by compiling lp4j-api and lp4j-midi and installing JARs to local repository

**Comment by perkowitz** [comment]
@lhornby Glad you sorted it out. Actually, Issho shouldn't be dependent on lp4j at all (that was carried over from my Sequence project). I'll try removing the dependency entirely.

**Comment by perkowitz** [comment]
Try this: https://github.com/perkowitz/issho/pull/12
