### ISSUE TITLE
Can this drive Ableton instead of a drum module/sampler?

### ISSUE THREAD

**Issue by shankararunachalam** [perkowitz/issho#58]
I am beginning to explore this sequencer. The configuration I have in mind is:

1. Launchpad Pro connected to a Windows 10 computer, running Ableton Live Standard
2. Same Launchpad Pro running Hachi sequencer (either running on Pi or on Windows, whatever is supported)
3. LaunchPad Pro's Hachi-sequenced Midi out driving Ableton's software drum pack in an Ableton track

Is this feasible with Hachi at this point? Would be awesome to have this!

@perkowitz

**Comment by perkowitz** [comment]
Yes, that should be possible, though I haven't tested it. I also haven't gotten Hachi running on a Windows machine. However, if your goal is to sequence Live drumkits, have you tried running the Push emulator on Launchpad? http://www.controllerism.com/launchpad95-ableton-push-emulator

Anyway, I'm happy to help if you run into any problems getting Hachi running.

**Comment by shankararunachalam** [comment]
@perkowitz, thanks for the note! Hadn't come across the push emulator. One of my goals is to sequence Live drumkits. So, certainly looks very promising. 

Pi configuration worked well for me, but couldn't do anything with Windows as you mentioned. Perhaps I could delve a bit deeper and see if I could get that config working, since my primary machine in a windows workstation anyway. If I get anywhere with it, I will let you know!

**Comment by perkowitz** [comment]
I don't really know what would be involved in getting it working on Windows, so let me know if you figure it out!
