### ISSUE TITLE
Compile error in jdk9

### ISSUE THREAD

**Issue by shankararunachalam** [perkowitz/issho#59]
@perkowitz, I happened to have jdk9 and when I compiled, I got ambiguous reference errors since Java 9 now has a Module system (java.lang.Module) which clashes with the Module.java in Hachi. I switched to JDK8 to resolve this. Might be useful to handle this ambiguity and a future point.

**Comment by perkowitz** [comment]
It's taken a long time, but this should be fixed. I've updated to java 12, and fixed all the Module references so they're not ambiguous.
